#!/bin/bash
#SBATCH --job-name='T_n'
#SBATCH --account=your-account
#SBATCH --partition=your-partition
#SBATCH --time=00-00:30:00
#SBATCH --mem-per-cpu=1000MB
#SBATCH --gpus-per-task=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --error='error.out'
#SBATCH --mail-type=FAIL

# This is the file which will submit a standard vasp job to the cluster.
srun vasp_std