#!/bin/bash
#SBATCH --job-name='SGUSCHI'
#SBATCH --partition=your-partition
#SBATCH --account=your-account
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=04-00:00:00
#SBATCH --mem-per-cpu=2000MB
#SBATCH --mail-type=ALL

#This file shows that masterscript to run SGUSCHI on the cluster.
#Must be submitted to cluster using sbatch or the like. 
#Permissions to run jobs from compute nodes also needed.

# Load modules
module load slurm
module load 2025
module load python/3.11.9
module load py-numpy
module load py-tqdm
module load py-scipy
module load py-pandas

# Set paths
PATH=~/home/pdwurzner/bin:$PATH
Volsearch_Cont="/home/pdwurzner/SGUSCHI/SGUSCHI/src/dependencies/SLUSCHI_mod/volsearch_cont"
SummaryScript="/home/pdwurzner/SGUSCHI/SGUSCHI/src/utils/SimulationSummary.py"

#Start summary table
python $SummaryScript "$PWD" --watch-daemon --interval 60 --oxparams OxParams --quiet

# Run volsearch_cont for all temperature/case combinations
for temp in 873 973 1073 1273; do
    for case in 1 2 3 4; do
        cd ${temp}_${case}/Dir_VolSearch
        $Volsearch_Cont >> "../log.out" 2>&1 &
        cd ../../
    done
done

wait
