#!/bin/csh

# General Purpose of this script is to adjsut the timestep of MD simulations
# based off of how quickly the SCF calculations converge. 
# Fast convergence allows for larger timestep. 

set sluschipath = ""
if ( $?sguschipath ) set sluschipath = "$sguschipath"
if ( "$sluschipath" == "" ) set sluschipath = `grep sluschipath ~/.sluschi.rc | cut -d'=' -f2 | tr -d '\r'`

# Add path prefix
$sluschipath/getinfo.csh adj_potim job.in > /dev/null
if ( $? == 0 ) then
  @ flag_adj = `$sluschipath/getinfo.csh adj_potim job.in`
else
  @ flag_adj = 1
endif

# get POTIM, NSW
set potim = `grep 'POTIM  =' OUTCAR | awk '{print $3}'`
if ( -d anal/history ) then
echo $potim > anal/history/potim
endif
@ nsw = `grep POSI OUTCAR | grep -v ML | wc -l`
@ nswd2 = `awk 'BEGIN{print ('$nsw'-'$nsw'%2)/2}'`
@ nswd4 = `awk 'BEGIN{print ('$nsw'-'$nsw'%4)/4}'`
if ( $flag_adj == 1 ) then
  # get tgt_nelm
  $sluschipath/getinfo.csh tgt_nelm job.in > /dev/null
  if ( $? == 0 ) then
    @ target = `$sluschipath/getinfo.csh tgt_nelm job.in`
  else
    @ target = 4
  endif
  @ targetp1 = $target + 1

  # get medium of nelm
  set NStep = `grep -B1 E0 OSZICAR | grep -v E0 | grep -v '\-\-' | awk '{print $2}' | sort -n | head -$nswd2 | tail -1`
  if ( $NStep <  $target ) then
    set potim = `awk 'BEGIN{print '$potim'+0.2}'`
    awk 'BEGIN{if ('$potim' > 3.0) exit 1}'
    if ( $? == 1 ) set potim = 3.0
    $sluschipath/UpdateINCAR POTIM $potim
  else if ( $NStep == $target ) then
    set NStep2 = `grep -B1 E0 OSZICAR | grep -v E0 | grep -v '\-\-' | awk '{print $2}' | sort -n | tail -$nswd4 | head -1`
    if ( $NStep2 == $target ) then
      # decrease POTIM ?
      set a=`grep E0 OSZICAR -B1 | grep -v E0 | grep -v '\-\-' | awk '{print $4}' | sort -n | tail -$nswd4 | head -1`
      set b=`grep E0 OSZICAR -B1 | grep -v E0 | grep -v '\-\-' | awk '{print $4}' | sort -n | head -$nswd4 | tail -1`
      awk 'BEGIN{if ('$a' < 4.e-5 && '$a' > -4.e-5 && '$b' < 4.e-5 && '$b' > -4.e-5) exit 1}'
      if ( $? ) then
        set potim = `awk 'BEGIN{print '$potim'+0.1}'`
        awk 'BEGIN{if ('$potim' > 3.0) exit 1}'
        if ( $? == 1 ) set potim = 3.0
      endif
    endif
    $sluschipath/UpdateINCAR POTIM $potim
  else if ( $NStep == $targetp1 ) then
  # increase POTIM ?
#    @ NLast10 = `grep E0 OSZICAR -B1 | grep -v E0 | grep -v '\-\-' | tail -10 | awk '{print $2}' | sort | head -1`
#    if ( $NLast10 > $target ) then
      set potim = `awk 'BEGIN{print '$potim'-0.1}'`
#    endif
    awk 'BEGIN{if ('$potim' < 0.4) exit 1}'
    if ( $? == 1 ) set potim = 0.4
    $sluschipath/UpdateINCAR POTIM $potim
  else 
    set potim = `awk 'BEGIN{print '$potim'-0.2}'`
    awk 'BEGIN{if ('$potim' < 0.4) exit 1}'
    if ( $? == 1 ) set potim = 0.4
    $sluschipath/UpdateINCAR POTIM $potim
  endif
  echo Adjust POTIM to $potim
else
  echo Maintain POTIM at $potim
endif
