#!/bin/csh

set failure_marker = sguschi_failed
rm -f $failure_marker

set sluschipath = `grep sluschipath ~/.sluschi.rc | cut -d'=' -f2 | tr -d '\r'`
if ( "$sluschipath" == "" ) then
  echo FATAL volsearch_cont: could not read sluschipath from ~/.sluschi.rc.
  touch $failure_marker
  exit 1
endif

#liquid?
$sluschipath/getinfo.csh thmexp_liq job.in > /dev/null
if ( $? == 0 ) then
  set flag_liq_value = `$sluschipath/getinfo.csh thmexp_liq job.in`
  if ( "$flag_liq_value" == "" ) then
    @ flag_liq = 0
  else
    @ flag_liq = $flag_liq_value
  endif
else
  @ flag_liq = 0
endif

#only?
set only = `$sluschipath/getinfo.csh thmexp_only job.in`
if ( "$only" == "" ) set only = 0
set vaspcmd = `$sluschipath/getinfo.csh vaspcmd job.in`
set temp = `$sluschipath/getinfo.csh temp job.in`
if ( "$vaspcmd" == "" ) then
  echo FATAL volsearch_cont: missing vaspcmd in job.in.
  touch $failure_marker
  exit 1
endif
if ( "$temp" == "" ) then
  echo FATAL volsearch_cont: missing temp in job.in.
  touch $failure_marker
  exit 1
endif
sed -i '/NBANDS/d' INCAR
set sigma = `awk -v a="0.000086" -v b=$temp 'BEGIN{print (b*a)}'`
if ( "$sigma" == "" ) then
  echo FATAL volsearch_cont: failed to calculate SIGMA from temp $temp.
  touch $failure_marker
  exit 1
endif

#$sluschipath/UpdateINCAR PREC normal
$sluschipath/UpdateINCAR SIGMA $sigma
if ( $? != 0 ) then
  echo FATAL volsearch_cont: failed to update SIGMA.
  touch $failure_marker
  exit 1
endif
$sluschipath/UpdateINCAR TEBEG $temp 
if ( $? != 0 ) then
  echo FATAL volsearch_cont: failed to update TEBEG.
  touch $failure_marker
  exit 1
endif
$sluschipath/UpdateINCAR TEEND $temp 
if ( $? != 0 ) then
  echo FATAL volsearch_cont: failed to update TEEND.
  touch $failure_marker
  exit 1
endif
$sluschipath/UpdateINCAR NSW 80
if ( $? != 0 ) then
  echo FATAL volsearch_cont: failed to update NSW.
  touch $failure_marker
  exit 1
endif
$sluschipath/UpdateINCAR SMASS 0 
if ( $? != 0 ) then
  echo FATAL volsearch_cont: failed to update SMASS.
  touch $failure_marker
  exit 1
endif

# submit the first job
set nstep=1
while ( -d $nstep )
  @ nstep = $nstep + 1
end
echo === Continue running with JOB $nstep ===

# initialize flags
@ stopflag = 0
@ count = 0
@ flag_gamma = 0

while ($stopflag == 0)

  sleep 60 ############################################################

  if ( -e OUTCAR ) then
  grep -s "Total CPU" OUTCAR > /dev/null
  if (! $?) then # Job is done

    echo ====== JOB $nstep DONE ======

    @ natom = `grep 'NIONS =' OUTCAR | tail -1 | awk '{print $12}'`
    echo $natom > natom

    @ pressure_fallback = 0
    set pressure_fallback_reason = ""
    set pressure_Pulay = "N/A"
    set pressure_kinetic = "N/A"
    set pressure_target = "N/A"

    if ( $count == 0 ) then
      echo --- Calculate Pulay stress... ---
      $sluschipath/PressurePulay > /dev/null
      if ( $? != 0 ) then
        echo WARNING volsearch_cont: PressurePulay failed; skipping pressure-controlled lattice update for this job.
        @ pressure_fallback = 1
        set pressure_fallback_reason = "PressurePulay failed"
      endif
    endif
    @ count = $count + 1
    if ( $count == 10 ) @ count = 0
    if ( -s pressure_Pulay.out ) then
      set pressure_Pulay = `cat pressure_Pulay.out`
    else if ( $pressure_fallback == 0 ) then
      echo WARNING volsearch_cont: pressure_Pulay.out is missing or empty; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "pressure_Pulay.out is missing or empty"
    endif

    $sluschipath/GetPTE # get P, T and E
    if ( $? != 0 ) then
      echo WARNING volsearch_cont: GetPTE failed; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "GetPTE failed"
    endif
    rm -f pressure3.out pressure3_total.out
    if ( $pressure_fallback == 0 ) then
    grep 'in kB' OUTCAR -B1 | grep -v 'in kB' | grep -v '\-\-' | grep -v CPU | grep -v cpu | awk 'function isnum(x){return x ~ /^[+-]?(([0-9]+[.]?[0-9]*)|([.][0-9]+))([EeDd][+-]?[0-9]+)?$/} NF >= 7 {ok=1; for (i=2;i<=7;i++) if (!isnum($i)) ok=0; if (ok) print $2,$3,$4,$5,$6,$7}' > pressure3.out # get Pxx, Pyy, Pzz, Pxy, Pyz, Pzx
    if ( ! -s pressure3.out ) then
      echo WARNING volsearch_cont: pressure3.out has no valid numeric stress rows after parsing OUTCAR; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "pressure3.out has no valid numeric stress rows"
    endif
    endif
    if ( $pressure_fallback == 0 ) then
    awk 'function isnum(x){return x ~ /^[+-]?(([0-9]+[.]?[0-9]*)|([.][0-9]+))([EeDd][+-]?[0-9]+)?$/} {if (NF != 6) bad=1; for (i=1;i<=NF;i++) if (!isnum($i)) bad=1; n++} END{if (bad || n < 1) exit 1}' pressure3.out
    if ( $? != 0 ) then
      echo WARNING volsearch_cont: pressure3.out must contain only six-column numeric stress rows; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "pressure3.out has malformed stress rows"
    endif
    endif
    if ( $pressure_fallback == 0 ) then
    set volume=`grep volume/ion OUTCAR | tail -1 | awk '{print $5}'`
    if ( "$volume" == "" ) then
      echo WARNING volsearch_cont: could not extract volume/ion from OUTCAR; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "could not extract volume/ion from OUTCAR"
    endif
    endif
    if ( $pressure_fallback == 0 ) then
    awk -v c="$volume" 'BEGIN{if (c+0 > 0) exit 0; exit 1}'
    if ( $? != 0 ) then
      echo WARNING volsearch_cont: invalid volume/ion value $volume; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "invalid volume/ion value"
    endif
    endif
    if ( $pressure_fallback == 0 ) then
    set temp=`grep TEEND INCAR | tail -1 | awk '{print $3}'`
    if ( "$temp" == "" ) then
      echo WARNING volsearch_cont: could not extract TEEND from INCAR; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "could not extract TEEND from INCAR"
    endif
    endif
    if ( $pressure_fallback == 0 ) then
    set pressure_kinetic=`awk -v k="1.38e-23" -v a="1.0e22" -v b="$temp" -v c="$volume" 'BEGIN{if (c+0 <= 0 || b == "") exit 1; printf("%.5f\n", (k*b/c*a))}'`
    if ( $? != 0 || "$pressure_kinetic" == "" ) then
      echo WARNING volsearch_cont: failed to calculate kinetic pressure; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "failed to calculate kinetic pressure"
    else
      echo $pressure_kinetic > pressure_kinetic.out
    endif
    endif
    if ( $pressure_fallback == 0 ) then
    awk 'function isnum(x){return x ~ /^[+-]?(([0-9]+[.]?[0-9]*)|([.][0-9]+))([EeDd][+-]?[0-9]+)?$/} NF > 0 {if (!isnum($1)) bad=1; n=1; exit} END{if (bad || n < 1) exit 1}' pressure_kinetic.out
    if ( $? != 0 ) then
      echo WARNING volsearch_cont: pressure_kinetic.out is missing or non-numeric; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "pressure_kinetic.out is missing or non-numeric"
    endif
    endif
    if ( $pressure_fallback == 0 ) then
    awk 'function isnum(x){return x ~ /^[+-]?(([0-9]+[.]?[0-9]*)|([.][0-9]+))([EeDd][+-]?[0-9]+)?$/} NF > 0 {if (!isnum($1)) bad=1; n=1; exit} END{if (bad || n < 1) exit 1}' pressure_Pulay.out
    if ( $? != 0 ) then
      echo WARNING volsearch_cont: pressure_Pulay.out is missing or non-numeric; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "pressure_Pulay.out is missing or non-numeric"
    endif
    endif
    if ( $pressure_fallback == 0 ) then
    set cell_volume = `grep 'volume of cell' OUTCAR | tail -1 | awk '{print $5}'`
    if ( "$cell_volume" == "" ) then
      echo WARNING volsearch_cont: could not extract volume of cell from OUTCAR; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "could not extract volume of cell from OUTCAR"
    endif
    endif
    if ( $pressure_fallback == 0 ) then
    awk -v v="$cell_volume" 'function isnum(x){return x ~ /^[+-]?(([0-9]+[.]?[0-9]*)|([.][0-9]+))([EeDd][+-]?[0-9]+)?$/} BEGIN{gsub(/[Dd]/,"E",v); if (isnum(v) && v+0 > 0) exit 0; exit 1}'
    if ( $? != 0 ) then
      echo WARNING volsearch_cont: invalid volume of cell value $cell_volume; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "invalid volume of cell value"
    else
      echo $cell_volume >> volume.out
    endif
    endif

    if ( $pressure_fallback == 0 ) then
    set pressure_target = `$sluschipath/getinfo.csh press job.in`
    if ( "$pressure_target" == "" ) then
      echo WARNING volsearch_cont: missing press in job.in; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "missing press in job.in"
    else
      echo $pressure_target  > pressure_target.out
    endif
    endif
    if ( $pressure_fallback == 0 ) then
    awk 'function isnum(x){return x ~ /^[+-]?(([0-9]+[.]?[0-9]*)|([.][0-9]+))([EeDd][+-]?[0-9]+)?$/} NF > 0 {if (!isnum($1)) bad=1; n=1; exit} END{if (bad || n < 1) exit 1}' pressure_target.out
    if ( $? != 0 ) then
      echo WARNING volsearch_cont: pressure_target.out is missing or non-numeric; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "pressure_target.out is missing or non-numeric"
    endif
    endif
    if ( $pressure_fallback == 0 ) then
    awk 'function isnum(x){return x ~ /^[+-]?(([0-9]+[.]?[0-9]*)|([.][0-9]+))([EeDd][+-]?[0-9]+)?$/} NF > 0 {last=$1; seen=1} END{gsub(/[Dd]/,"E",last); if (!seen || !isnum(last) || last+0 <= 0) exit 1}' volume.out
    if ( $? != 0 ) then
      echo WARNING volsearch_cont: volume.out is missing or its last value is invalid; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "volume.out is missing or its last value is invalid"
    endif
    endif
    
    if ( $pressure_fallback == 0 ) then
    $sluschipath/PressureAvg.x 
    if ( $? != 0 || ! -s pressure3_total.out ) then
      echo WARNING volsearch_cont: PressureAvg.x failed or did not create pressure3_total.out; skipping pressure-controlled lattice update for this job.
      @ pressure_fallback = 1
      set pressure_fallback_reason = "PressureAvg.x failed"
    endif
    endif

    head -5 POSCAR | tail -3 > lattice.out
    set v1 = `head -1 lattice.out`
    set v2 = `head -2 lattice.out | tail -1`
    set v3 = `head -3 lattice.out | tail -1`
    rm lattice.out
    if ( $pressure_fallback == 1 ) then
      set p = "0.000000 0.000000 0.000000 0.000000 0.000000 0.000000"
      echo $p > pressure3_total.out
    else
      set p = `cat pressure3_total.out`
      @ pcount = `echo $p | awk '{print NF}'`
      if ( $pcount != 6 ) then
        echo WARNING volsearch_cont: pressure3_total.out does not contain six pressure components; skipping pressure-controlled lattice update for this job.
        @ pressure_fallback = 1
        set pressure_fallback_reason = "pressure3_total.out does not contain six pressure components"
        set p = "0.000000 0.000000 0.000000 0.000000 0.000000 0.000000"
        echo $p > pressure3_total.out
      endif
    endif
    set pxx = `echo $p | awk '{print $1}'`
    set pyy = `echo $p | awk '{print $2}'`
    set pzz = `echo $p | awk '{print $3}'`
    set pxy = `echo $p | awk '{print $4}'`
    set pyz = `echo $p | awk '{print $5}'`
    set pxz = `echo $p | awk '{print $6}'`
    if ( $pressure_fallback == 1 ) then
      echo WARNING volsearch_cont: pressure update skipped for JOB $nstep \($pressure_fallback_reason\); current lattice will be reused.
    else
      echo $v1 $v2 $v3 $p >> lattice_pressure_history.out
      echo Pulay stress $pressure_Pulay, kinetic pressure $pressure_kinetic, pressure target $pressure_target kbar.
      echo "--- LATTICE VECTORS --- \t\t --- PRESSURE ---"
      echo "$v1 \t $pxx $pxy $pxz"
      echo "$v2 \t $pxy $pyy $pyz"
      echo "$v3 \t $pxz $pyz $pzz"
    endif

    # --- FIX 2: Added $sluschipath/ prefix ---
    set navg_pressure = `$sluschipath/getinfo.csh navg job.in`
    set factor_divide = `$sluschipath/getinfo.csh factor job.in`
    if ( "$navg_pressure" == "" ) then
      echo FATAL volsearch_cont: missing navg in job.in.
      touch $failure_marker
      exit 1
    endif
    if ( "$factor_divide" == "" ) then
      echo FATAL volsearch_cont: missing factor in job.in.
      touch $failure_marker
      exit 1
    endif
    awk -v f="$factor_divide" 'BEGIN{if (f+0 != 0) exit 0; exit 1}'
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: invalid factor value $factor_divide.
      touch $failure_marker
      exit 1
    endif
    echo $navg_pressure > param.in
    echo $factor_divide >> param.in
    rm -f lattice_predict.out
    if ( $pressure_fallback == 1 ) then
      echo $v1 > lattice_predict.out
      echo $v2 >> lattice_predict.out
      echo $v3 >> lattice_predict.out
      echo WARNING volsearch_cont: DetermineSize.x skipped for JOB $nstep because pressure update failed.
    else
      $sluschipath/DetermineSize.x
      if ( $? != 0 || ! -s lattice_predict.out ) then
        echo FATAL volsearch_cont: DetermineSize.x failed or did not create lattice_predict.out.
        touch $failure_marker
        exit 1
      endif
    endif
    
    echo --- ADJUST INCAR TAGS ---
    $sluschipath/AdjustPOTIM
    if ( $? != 0 ) then
      echo WARNING volsearch_cont: AdjustPOTIM failed; keeping current POTIM.
    endif
    $sluschipath/AdjustNBANDS
    if ( $? != 0 ) then
      echo WARNING volsearch_cont: AdjustNBANDS failed; keeping current NBANDS/default.
    endif
    $sluschipath/AdjustBMIX
    if ( $? != 0 ) then
      echo WARNING volsearch_cont: AdjustBMIX failed; keeping current BMIX.
    endif
    mkdir $nstep
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: failed to create step folder $nstep.
      touch $failure_marker
      exit 1
    endif
    cp INCAR KPOINTS POSCAR OSZICAR $nstep
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: failed to copy inputs into step folder $nstep.
      touch $failure_marker
      exit 1
    endif
    set nkpts_value = `grep NKPTS OUTCAR | awk '{print $4}'`
    if ( "$nkpts_value" == "" ) then
      echo FATAL volsearch_cont: could not extract NKPTS from OUTCAR.
      touch $failure_marker
      exit 1
    endif
    @ NKPTS = $nkpts_value
    # --- FIX 2: Added $sluschipath/ prefix ---
    set gamma_value = `$sluschipath/getinfo.csh gamma_possible job.in`
    if ( "$gamma_value" == "" ) set gamma_value = 0
    @ gamma = $gamma_value
    if ( $NKPTS == 1 && $gamma == 1 && -e ../jobsub_gamma ) then
      if ( $flag_gamma == 0 ) then
        cp IBZKPT KPOINTS
        rm -f WAVECAR
        @ flag_gamma = 1
      endif
      cp ../jobsub_gamma jobsub
      if ( $? != 0 ) then
        echo FATAL volsearch_cont: failed to copy ../jobsub_gamma.
        touch $failure_marker
        exit 1
      endif
    else
      cp ../jobsub .
      if ( $? != 0 ) then
        echo FATAL volsearch_cont: failed to copy ../jobsub.
        touch $failure_marker
        exit 1
      endif
    endif
    mv OUTCAR $nstep
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: failed to move OUTCAR into step folder $nstep.
      touch $failure_marker
      exit 1
    endif
    touch OUTCAR

    # --- FIX 2: Added $sluschipath/ prefix to ALL below ---
    $sluschipath/getinfo.csh thmexp_cnvg job.in > /dev/null
    if ( $? == 0 ) then
      $sluschipath/getinfo.csh thmexp_cnvg job.in > thmexp.in
    else
      echo 20.0 > thmexp.in
    endif
    $sluschipath/getinfo.csh thmexp_max job.in > /dev/null
    if ( $? == 0 ) then
      set maxstep_value = `$sluschipath/getinfo.csh thmexp_max job.in`
      if ( "$maxstep_value" == "" ) then
        @ maxstep = 5
      else
        @ maxstep = $maxstep_value
      endif
    else
      @ maxstep = 5
    endif
    $sluschipath/getinfo.csh thmexp_min job.in > /dev/null
    if ( $? == 0 ) then
      set minstep_value = `$sluschipath/getinfo.csh thmexp_min job.in`
      if ( "$minstep_value" == "" ) then
        @ minstep = 1
      else
        @ minstep = $minstep_value
      endif
    else
      @ minstep = 1
    endif
    
    if ( $pressure_fallback == 1 ) then
      @ stopflag = 0
      echo WARNING volsearch_cont: VolSearchStop.x skipped for JOB $nstep because no reliable pressure was available.
    else
      rm -f VolSearchStop.out
      $sluschipath/VolSearchStop.x
      if ( $? != 0 || ! -s VolSearchStop.out ) then
        echo FATAL volsearch_cont: VolSearchStop.x failed or did not create VolSearchStop.out.
        touch $failure_marker
        exit 1
      endif
      set stopflag_value = `cat VolSearchStop.out`
      if ( "$stopflag_value" == "" ) then
        echo FATAL volsearch_cont: VolSearchStop.out is empty.
        touch $failure_marker
        exit 1
      endif
      @ stopflag = $stopflag_value
    endif
    if ( -d $maxstep )  @ stopflag = 1
    if ( ! -d $minstep )  @ stopflag = 0
    if ( $stopflag == 1 ) then
      if ( $flag_liq == 1 || $only == 1 ) then
      $sluschipath/collect.csh OUTCAR
      grep 'energy  without entropy' OUTCAR_collect | awk '{print $4}' > for_avg
      $sluschipath/avg_std.x
      echo You may be interested in the average energy, especially for the calculation of fusion heat.
      echo For detailed theory, read \"Understanding Molecular Simulations, from Algorithms to Applications\" by D. Frenkel and B. Smit, Page 525-530
      echo To obtain average energy and standard error, locate \(N,B,P\) such that...
      echo 1. N is small enough, i.e., the MD trajectory is properly truncated.
      echo 2. the P vs. B curve reaches a plateau, i.e., B is large enough, much larger than correlation time.
      echo Last N MD steps for average, B \(size of block\), nB \(number of blocks\), P \(look for plateau of P vs. B \), Average Total Energy without electronic entropy, standard error
      cat avg_std_detail.out
      @ navg1 = `head -1 avg_std.out | awk '{print $1}'`
      set avg1 = `head -1 avg_std.out | awk '{print $6}'`
      set std1 = `head -1 avg_std.out | awk '{print $7}'`
      echo Based on last $navg1 steps, the energy is $avg1 +/- $std1 eV per atom.
      @ navg2 =  `head -2 avg_std.out | tail -1 |  awk '{print $1}'`
      set avg2 = `head -2 avg_std.out | tail -1 |  awk '{print $6}'`
      set std2 = `head -2 avg_std.out | tail -1 |  awk '{print $7}'`
      echo Based on last $navg2 steps, the energy is $avg2 +/- $std2 eV per atom.
      @ navg3 =  `tail -1 avg_std.out | awk '{print $1}'`
      set avg3 = `tail -1 avg_std.out | awk '{print $6}'`
      set std3 = `tail -1 avg_std.out | awk '{print $7}'`
      echo Based on last $navg3 steps, the energy is $avg3 +/- $std3 eV per atom.
      echo Choose a value properly: 1. steps as many as possible 2. energy converges
      mv avg_std.out avg_std_energy.out
      mv avg_std_detail.out avg_std_detail_energy.out
      $sluschipath/Converge
      set en_correction = `cat energy_converge.out`
      set avg1 = `awk 'BEGIN{print '$avg1'+'$en_correction'}'`
      set avg2 = `awk 'BEGIN{print '$avg2'+'$en_correction'}'`
      set avg3 = `awk 'BEGIN{print '$avg3'+'$en_correction'}'`
      echo Based on last $navg1 steps, the energy is $avg1 +/- $std1 eV per atom.
      echo Based on last $navg2 steps, the energy is $avg2 +/- $std2 eV per atom.
      echo Based on last $navg3 steps, the energy is $avg3 +/- $std3 eV per atom.
      echo Choose a value properly: 1. steps as many as possible 2. energy converges
      cp volume.out for_avg
      $sluschipath/avg_std.x
      @ navg1 = `head -1 avg_std.out | awk '{print $1}'`
      set avg1 = `head -1 avg_std.out | awk '{print $6}'`
      set std1 = `head -1 avg_std.out | awk '{print $7}'`
      echo Based on last $navg1 steps, the volume is $avg1 +/- $std1 Ang3 per atom.
      @ navg2 =  `head -2 avg_std.out | tail -1 |  awk '{print $1}'`
      set avg2 = `head -2 avg_std.out | tail -1 |  awk '{print $6}'`
      set std2 = `head -2 avg_std.out | tail -1 |  awk '{print $7}'`
      echo Based on last $navg2 steps, the volume is $avg2 +/- $std2 Ang3 per atom.
      @ navg3 =  `tail -1 avg_std.out | awk '{print $1}'`
      set avg3 = `tail -1 avg_std.out | awk '{print $6}'`
      set std3 = `tail -1 avg_std.out | awk '{print $7}'`
      echo Based on last $navg3 steps, the volume is $avg3 +/- $std3 Ang3 per atom.
      echo Choose a value properly: 1. steps as many as possible 2. volume converges
      mv avg_std.out avg_std_volume.out
      mv avg_std_detail.out avg_std_detail_volume.out
      endif
    else
      if ( $flag_liq == 1 && $nstep == 6 ) then
        set temp = `$sluschipath/getinfo.csh temp job.in` # (Fixed here too just in case)
        if ( "$temp" == "" ) then
          echo FATAL volsearch_cont: missing temp in job.in while resetting liquid run temperature.
          touch $failure_marker
          exit 1
        endif
        $sluschipath/UpdateINCAR TEBEG $temp
        if ( $? != 0 ) then
          echo FATAL volsearch_cont: failed to update TEBEG for liquid run.
          touch $failure_marker
          exit 1
        endif
        $sluschipath/UpdateINCAR TEEND $temp
        if ( $? != 0 ) then
          echo FATAL volsearch_cont: failed to update TEEND for liquid run.
          touch $failure_marker
          exit 1
        endif
      endif
      if ( ! -s CONTCAR ) then
        echo FATAL volsearch_cont: missing CONTCAR before building next POSCAR.
        touch $failure_marker
        exit 1
      endif
      if ( ! -s lattice_predict.out ) then
        echo FATAL volsearch_cont: missing lattice_predict.out before building next POSCAR.
        touch $failure_marker
        exit 1
      endif
      head -2 CONTCAR > POSCAR
      cat lattice_predict.out >> POSCAR
      tail -n+6 CONTCAR >> POSCAR
      if ( $? != 0 || ! -s POSCAR ) then
        echo FATAL volsearch_cont: failed to build next POSCAR.
        touch $failure_marker
        exit 1
      endif
      
      python "$sluschipath/../../workflow/OxidationStep.py"
      if ( $? != 0 ) then
        echo FATAL volsearch_cont: OxidationStep.py failed; no new job submitted.
        touch $failure_marker
        exit 1
      endif

      $vaspcmd jobsub >> jobsub.log
      if ( $? != 0 ) then
        echo FATAL volsearch_cont: job submission command failed.
        touch $failure_marker
        exit 1
      endif
      set nstep = `expr $nstep + 1`
      echo Job $nstep submitted. Waiting for job $nstep to finish... 
    endif
  endif
  endif
end
echo total pressure is $p kbar, which meets the target $pressure_target within 20 kbar. Volume search completed.
echo killing script...
cp CONTCAR $nstep/OUTCAR ..
cp INCAR ..
touch volsearch_is_done
