#!/bin/csh

set failure_marker = sguschi_failed
rm -f $failure_marker

set sluschipath = `grep sluschipath ~/.sluschi.rc | cut -d'=' -f2 | tr -d '\r'`
if ( "$sluschipath" == "" ) then
  echo FATAL volsearch_cont: could not read sluschipath from ~/.sluschi.rc.
  touch $failure_marker
  exit 1
endif

#liquid?
$sluschipath/getinfo.csh thmexp_liq job.in > /dev/null
if ( $? == 0 ) then
  set flag_liq_value = `$sluschipath/getinfo.csh thmexp_liq job.in`
  if ( "$flag_liq_value" == "" ) then
    @ flag_liq = 0
  else
    @ flag_liq = $flag_liq_value
  endif
else
  @ flag_liq = 0
endif

#only?
set only = `$sluschipath/getinfo.csh thmexp_only job.in`
if ( "$only" == "" ) set only = 0
set vaspcmd = `$sluschipath/getinfo.csh vaspcmd job.in`
set temp = `$sluschipath/getinfo.csh temp job.in`
if ( "$vaspcmd" == "" ) then
  echo FATAL volsearch_cont: missing vaspcmd in job.in.
  touch $failure_marker
  exit 1
endif
if ( "$temp" == "" ) then
  echo FATAL volsearch_cont: missing temp in job.in.
  touch $failure_marker
  exit 1
endif
sed -i '/NBANDS/d' INCAR
set sigma = `awk -v a="0.000086" -v b=$temp 'BEGIN{print (b*a)}'`
if ( "$sigma" == "" ) then
  echo FATAL volsearch_cont: failed to calculate SIGMA from temp $temp.
  touch $failure_marker
  exit 1
endif

#$sluschipath/UpdateINCAR PREC normal
$sluschipath/UpdateINCAR SIGMA $sigma
if ( $? != 0 ) then
  echo FATAL volsearch_cont: failed to update SIGMA.
  touch $failure_marker
  exit 1
endif
$sluschipath/UpdateINCAR TEBEG $temp 
if ( $? != 0 ) then
  echo FATAL volsearch_cont: failed to update TEBEG.
  touch $failure_marker
  exit 1
endif
$sluschipath/UpdateINCAR TEEND $temp 
if ( $? != 0 ) then
  echo FATAL volsearch_cont: failed to update TEEND.
  touch $failure_marker
  exit 1
endif
$sluschipath/UpdateINCAR NSW 80
if ( $? != 0 ) then
  echo FATAL volsearch_cont: failed to update NSW.
  touch $failure_marker
  exit 1
endif
$sluschipath/UpdateINCAR SMASS 0 
if ( $? != 0 ) then
  echo FATAL volsearch_cont: failed to update SMASS.
  touch $failure_marker
  exit 1
endif

# submit the first job
set nstep=1
while ( -d $nstep )
  @ nstep = $nstep + 1
end
echo === Continue running with JOB $nstep ===

# initialize flags
@ stopflag = 0
@ count = 0
@ flag_gamma = 0

while ($stopflag == 0)

  sleep 60 ############################################################

  if ( -e OUTCAR ) then
  grep -s "Total CPU" OUTCAR > /dev/null
  if (! $?) then # Job is done

    echo ====== JOB $nstep DONE ======

    @ natom = `grep 'NIONS =' OUTCAR | tail -1 | awk '{print $12}'`
    echo $natom > natom

    if ( $count == 0 ) then
      echo --- Calculate Pulay stress... ---
      $sluschipath/PressurePulay > /dev/null
      if ( $? != 0 ) then
        echo FATAL volsearch_cont: PressurePulay failed.
        touch $failure_marker
        exit 1
      endif
    endif
    @ count = $count + 1
    if ( $count == 10 ) @ count = 0
    set pressure_Pulay = `cat pressure_Pulay.out`
    if ( "$pressure_Pulay" == "" ) then
      echo FATAL volsearch_cont: pressure_Pulay.out is missing or empty.
      touch $failure_marker
      exit 1
    endif

    $sluschipath/GetPTE # get P, T and E
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: GetPTE failed.
      touch $failure_marker
      exit 1
    endif
    rm -f pressure3.out pressure3_total.out
    grep 'in kB' OUTCAR -B1 | grep -v 'in kB' | grep -v ' 0.00 ' | grep -v '\-\-' | grep -v CPU | grep -v cpu | awk '{print $2,$3,$4,$5,$6,$7}' > pressure3.out # get Pxx, Pyy, Pzz, Pxy, Pyz, Pzx
    if ( ! -s pressure3.out ) then
      echo FATAL volsearch_cont: pressure3.out is empty after parsing OUTCAR stress.
      touch $failure_marker
      exit 1
    endif
    set volume=`grep volume/ion OUTCAR | awk '{print $5}'`
    if ( "$volume" == "" ) then
      echo FATAL volsearch_cont: could not extract volume/ion from OUTCAR.
      touch $failure_marker
      exit 1
    endif
    awk -v c="$volume" 'BEGIN{if (c+0 > 0) exit 0; exit 1}'
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: invalid volume/ion value $volume.
      touch $failure_marker
      exit 1
    endif
    set temp=`grep TEEND INCAR | awk '{print $3}'`
    if ( "$temp" == "" ) then
      echo FATAL volsearch_cont: could not extract TEEND from INCAR.
      touch $failure_marker
      exit 1
    endif
    set pressure_kinetic=`awk -v k="1.38e-23" -v a="1.0e22" -v b="$temp" -v c="$volume" 'BEGIN{if (c+0 <= 0 || b == "") exit 1; printf("%.5f\n", (k*b/c*a))}'`
    if ( $? != 0 || "$pressure_kinetic" == "" ) then
      echo FATAL volsearch_cont: failed to calculate kinetic pressure.
      touch $failure_marker
      exit 1
    endif
    echo $pressure_kinetic > pressure_kinetic.out
    grep 'volume of cell' OUTCAR | awk '{print $5}' >> volume.out


    set pressure_target = `$sluschipath/getinfo.csh press job.in`
    if ( "$pressure_target" == "" ) then
      echo FATAL volsearch_cont: missing press in job.in.
      touch $failure_marker
      exit 1
    endif
    echo $pressure_target  > pressure_target.out
    
    $sluschipath/PressureAvg.x 
    if ( $? != 0 || ! -s pressure3_total.out ) then
      echo FATAL volsearch_cont: PressureAvg.x failed or did not create pressure3_total.out.
      touch $failure_marker
      exit 1
    endif

    head -5 POSCAR | tail -3 > lattice.out
    set v1 = `head -1 lattice.out`
    set v2 = `head -2 lattice.out | tail -1`
    set v3 = `head -3 lattice.out | tail -1`
    rm lattice.out
    set p = `cat pressure3_total.out`
    @ pcount = `echo $p | awk '{print NF}'`
    if ( $pcount != 6 ) then
      echo FATAL volsearch_cont: pressure3_total.out does not contain six pressure components.
      touch $failure_marker
      exit 1
    endif
    set pxx = `echo $p | awk '{print $1}'`
    set pyy = `echo $p | awk '{print $2}'`
    set pzz = `echo $p | awk '{print $3}'`
    set pxy = `echo $p | awk '{print $4}'`
    set pyz = `echo $p | awk '{print $5}'`
    set pxz = `echo $p | awk '{print $6}'`
    echo $v1 $v2 $v3 $p >> lattice_pressure_history.out
    echo Pulay stress $pressure_Pulay, kinetic pressure $pressure_kinetic, pressure target $pressure_target kbar.
    echo "--- LATTICE VECTORS --- \t\t --- PRESSURE ---"
    echo "$v1 \t $pxx $pxy $pxz" 
    echo "$v2 \t $pxy $pyy $pyz"
    echo "$v3 \t $pxz $pyz $pzz"

    # --- FIX 2: Added $sluschipath/ prefix ---
    set navg_pressure = `$sluschipath/getinfo.csh navg job.in`
    set factor_divide = `$sluschipath/getinfo.csh factor job.in`
    if ( "$navg_pressure" == "" ) then
      echo FATAL volsearch_cont: missing navg in job.in.
      touch $failure_marker
      exit 1
    endif
    if ( "$factor_divide" == "" ) then
      echo FATAL volsearch_cont: missing factor in job.in.
      touch $failure_marker
      exit 1
    endif
    awk -v f="$factor_divide" 'BEGIN{if (f+0 != 0) exit 0; exit 1}'
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: invalid factor value $factor_divide.
      touch $failure_marker
      exit 1
    endif
    echo $navg_pressure > param.in
    echo $factor_divide >> param.in
    rm -f lattice_predict.out
    $sluschipath/DetermineSize.x
    if ( $? != 0 || ! -s lattice_predict.out ) then
      echo FATAL volsearch_cont: DetermineSize.x failed or did not create lattice_predict.out.
      touch $failure_marker
      exit 1
    endif
    
    echo --- ADJUST INCAR TAGS ---
    $sluschipath/AdjustPOTIM
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: AdjustPOTIM failed.
      touch $failure_marker
      exit 1
    endif
    $sluschipath/AdjustNBANDS
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: AdjustNBANDS failed.
      touch $failure_marker
      exit 1
    endif
    $sluschipath/AdjustBMIX
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: AdjustBMIX failed.
      touch $failure_marker
      exit 1
    endif
    mkdir $nstep
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: failed to create step folder $nstep.
      touch $failure_marker
      exit 1
    endif
    cp INCAR KPOINTS POSCAR OSZICAR $nstep
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: failed to copy inputs into step folder $nstep.
      touch $failure_marker
      exit 1
    endif
    set nkpts_value = `grep NKPTS OUTCAR | awk '{print $4}'`
    if ( "$nkpts_value" == "" ) then
      echo FATAL volsearch_cont: could not extract NKPTS from OUTCAR.
      touch $failure_marker
      exit 1
    endif
    @ NKPTS = $nkpts_value
    # --- FIX 2: Added $sluschipath/ prefix ---
    set gamma_value = `$sluschipath/getinfo.csh gamma_possible job.in`
    if ( "$gamma_value" == "" ) set gamma_value = 0
    @ gamma = $gamma_value
    if ( $NKPTS == 1 && $gamma == 1 && -e ../jobsub_gamma ) then
      if ( $flag_gamma == 0 ) then
        cp IBZKPT KPOINTS
        rm -f WAVECAR
        @ flag_gamma = 1
      endif
      cp ../jobsub_gamma jobsub
      if ( $? != 0 ) then
        echo FATAL volsearch_cont: failed to copy ../jobsub_gamma.
        touch $failure_marker
        exit 1
      endif
    else
      cp ../jobsub .
      if ( $? != 0 ) then
        echo FATAL volsearch_cont: failed to copy ../jobsub.
        touch $failure_marker
        exit 1
      endif
    endif
    mv OUTCAR $nstep
    if ( $? != 0 ) then
      echo FATAL volsearch_cont: failed to move OUTCAR into step folder $nstep.
      touch $failure_marker
      exit 1
    endif
    touch OUTCAR

    # --- FIX 2: Added $sluschipath/ prefix to ALL below ---
    $sluschipath/getinfo.csh thmexp_cnvg job.in > /dev/null
    if ( $? == 0 ) then
      $sluschipath/getinfo.csh thmexp_cnvg job.in > thmexp.in
    else
      echo 20.0 > thmexp.in
    endif
    $sluschipath/getinfo.csh thmexp_max job.in > /dev/null
    if ( $? == 0 ) then
      set maxstep_value = `$sluschipath/getinfo.csh thmexp_max job.in`
      if ( "$maxstep_value" == "" ) then
        @ maxstep = 5
      else
        @ maxstep = $maxstep_value
      endif
    else
      @ maxstep = 5
    endif
    $sluschipath/getinfo.csh thmexp_min job.in > /dev/null
    if ( $? == 0 ) then
      set minstep_value = `$sluschipath/getinfo.csh thmexp_min job.in`
      if ( "$minstep_value" == "" ) then
        @ minstep = 1
      else
        @ minstep = $minstep_value
      endif
    else
      @ minstep = 1
    endif
    
    rm -f VolSearchStop.out
    $sluschipath/VolSearchStop.x
    if ( $? != 0 || ! -s VolSearchStop.out ) then
      echo FATAL volsearch_cont: VolSearchStop.x failed or did not create VolSearchStop.out.
      touch $failure_marker
      exit 1
    endif
    set stopflag_value = `cat VolSearchStop.out`
    if ( "$stopflag_value" == "" ) then
      echo FATAL volsearch_cont: VolSearchStop.out is empty.
      touch $failure_marker
      exit 1
    endif
    @ stopflag = $stopflag_value
    if ( -d $maxstep )  @ stopflag = 1
    if ( ! -d $minstep )  @ stopflag = 0
    if ( $stopflag == 1 ) then
      if ( $flag_liq == 1 || $only == 1 ) then
      $sluschipath/collect.csh OUTCAR
      grep 'energy  without entropy' OUTCAR_collect | awk '{print $4}' > for_avg
      $sluschipath/avg_std.x
      echo You may be interested in the average energy, especially for the calculation of fusion heat.
      echo For detailed theory, read \"Understanding Molecular Simulations, from Algorithms to Applications\" by D. Frenkel and B. Smit, Page 525-530
      echo To obtain average energy and standard error, locate \(N,B,P\) such that...
      echo 1. N is small enough, i.e., the MD trajectory is properly truncated.
      echo 2. the P vs. B curve reaches a plateau, i.e., B is large enough, much larger than correlation time.
      echo Last N MD steps for average, B \(size of block\), nB \(number of blocks\), P \(look for plateau of P vs. B \), Average Total Energy without electronic entropy, standard error
      cat avg_std_detail.out
      @ navg1 = `head -1 avg_std.out | awk '{print $1}'`
      set avg1 = `head -1 avg_std.out | awk '{print $6}'`
      set std1 = `head -1 avg_std.out | awk '{print $7}'`
      echo Based on last $navg1 steps, the energy is $avg1 +/- $std1 eV per atom.
      @ navg2 =  `head -2 avg_std.out | tail -1 |  awk '{print $1}'`
      set avg2 = `head -2 avg_std.out | tail -1 |  awk '{print $6}'`
      set std2 = `head -2 avg_std.out | tail -1 |  awk '{print $7}'`
      echo Based on last $navg2 steps, the energy is $avg2 +/- $std2 eV per atom.
      @ navg3 =  `tail -1 avg_std.out | awk '{print $1}'`
      set avg3 = `tail -1 avg_std.out | awk '{print $6}'`
      set std3 = `tail -1 avg_std.out | awk '{print $7}'`
      echo Based on last $navg3 steps, the energy is $avg3 +/- $std3 eV per atom.
      echo Choose a value properly: 1. steps as many as possible 2. energy converges
      mv avg_std.out avg_std_energy.out
      mv avg_std_detail.out avg_std_detail_energy.out
      $sluschipath/Converge
      set en_correction = `cat energy_converge.out`
      set avg1 = `awk 'BEGIN{print '$avg1'+'$en_correction'}'`
      set avg2 = `awk 'BEGIN{print '$avg2'+'$en_correction'}'`
      set avg3 = `awk 'BEGIN{print '$avg3'+'$en_correction'}'`
      echo Based on last $navg1 steps, the energy is $avg1 +/- $std1 eV per atom.
      echo Based on last $navg2 steps, the energy is $avg2 +/- $std2 eV per atom.
      echo Based on last $navg3 steps, the energy is $avg3 +/- $std3 eV per atom.
      echo Choose a value properly: 1. steps as many as possible 2. energy converges
      cp volume.out for_avg
      $sluschipath/avg_std.x
      @ navg1 = `head -1 avg_std.out | awk '{print $1}'`
      set avg1 = `head -1 avg_std.out | awk '{print $6}'`
      set std1 = `head -1 avg_std.out | awk '{print $7}'`
      echo Based on last $navg1 steps, the volume is $avg1 +/- $std1 Ang3 per atom.
      @ navg2 =  `head -2 avg_std.out | tail -1 |  awk '{print $1}'`
      set avg2 = `head -2 avg_std.out | tail -1 |  awk '{print $6}'`
      set std2 = `head -2 avg_std.out | tail -1 |  awk '{print $7}'`
      echo Based on last $navg2 steps, the volume is $avg2 +/- $std2 Ang3 per atom.
      @ navg3 =  `tail -1 avg_std.out | awk '{print $1}'`
      set avg3 = `tail -1 avg_std.out | awk '{print $6}'`
      set std3 = `tail -1 avg_std.out | awk '{print $7}'`
      echo Based on last $navg3 steps, the volume is $avg3 +/- $std3 Ang3 per atom.
      echo Choose a value properly: 1. steps as many as possible 2. volume converges
      mv avg_std.out avg_std_volume.out
      mv avg_std_detail.out avg_std_detail_volume.out
      endif
    else
      if ( $flag_liq == 1 && $nstep == 6 ) then
        set temp = `$sluschipath/getinfo.csh temp job.in` # (Fixed here too just in case)
        if ( "$temp" == "" ) then
          echo FATAL volsearch_cont: missing temp in job.in while resetting liquid run temperature.
          touch $failure_marker
          exit 1
        endif
        $sluschipath/UpdateINCAR TEBEG $temp
        if ( $? != 0 ) then
          echo FATAL volsearch_cont: failed to update TEBEG for liquid run.
          touch $failure_marker
          exit 1
        endif
        $sluschipath/UpdateINCAR TEEND $temp
        if ( $? != 0 ) then
          echo FATAL volsearch_cont: failed to update TEEND for liquid run.
          touch $failure_marker
          exit 1
        endif
      endif
      if ( ! -s CONTCAR ) then
        echo FATAL volsearch_cont: missing CONTCAR before building next POSCAR.
        touch $failure_marker
        exit 1
      endif
      if ( ! -s lattice_predict.out ) then
        echo FATAL volsearch_cont: missing lattice_predict.out before building next POSCAR.
        touch $failure_marker
        exit 1
      endif
      head -2 CONTCAR > POSCAR
      cat lattice_predict.out >> POSCAR
      tail -n+6 CONTCAR >> POSCAR
      if ( $? != 0 || ! -s POSCAR ) then
        echo FATAL volsearch_cont: failed to build next POSCAR.
        touch $failure_marker
        exit 1
      endif
       
      python "$sluschipath/../../workflow/OxidationStep.py"
      if ( $? != 0 ) then
        echo FATAL volsearch_cont: OxidationStep.py failed; no new job submitted.
        touch $failure_marker
        exit 1
      endif
       
      $vaspcmd jobsub >> jobsub.log
      if ( $? != 0 ) then
        echo FATAL volsearch_cont: job submission command failed.
        touch $failure_marker
        exit 1
      endif
      set nstep = `expr $nstep + 1`
      echo Job $nstep submitted. Waiting for job $nstep to finish... 
    endif
  endif
  endif
end
echo total pressure is $p kbar, which meets the target $pressure_target within 20 kbar. Volume search completed.
echo killing script...
cp CONTCAR $nstep/OUTCAR ..
cp INCAR ..
touch volsearch_is_done
